@startuml
start
:Initialize sum to 0;
:Initialize i to 0;
repeat
  :Is i < 10?;
  if (yes) then (yes)
    :Add array[i] to sum;
    :Increment i;
  else (no)
    :Display sum;
  endif
repeat while (yes)
end
@enduml